import turtle as tr
def duga(n,r):
    for i in range(n // 2):
        tr.forward(r / n * 2 * 3.1415)
        tr.right(360 / n)
def round(n, r):
    for i in range(n):
        tr.forward(r / n * 2 * 3.1415)
        tr.right(360 / n)
def smile():
    tr.right(180)
    tr.color('yellow')
    tr.begin_fill()
    round(100,100)
    tr.end_fill()
    tr.right(180)
    tr.penup()
    tr.goto(20,150)
    tr.left(90)
    tr.pendown()
    tr.color('blue')
    tr.begin_fill()
    round(100,20)
    tr.penup()
    tr.goto(-20,150)
    tr.left(180)
    tr.pendown()
    round(100,20)
    tr.end_fill()
    tr.penup()
    tr.goto(0,120)
    tr.pendown()
    tr.color('black')
    tr.width(5)
    tr.forward(50)
    tr.penup()
    tr.goto(30,50)
    tr.pendown()
    tr.color('red')
    duga(100,30)

smile()
tr.done()