FPS: 30
windowsize: [1200, 500]
difficulty:
- 6 # Количество шаров
- 15 # Время жизни обычных шаров
- 3 # Время жизни супер шаров
- [10, 70] # Размеры обычных шаров
- [15, 40] # Размеры супершаров
- 100 # Скорости шаров
- 200 # Скорости супершаров
# Прямоугольники кнопок:
buttons:
- [20, 380, 150, 30]
- [20, 420, 150, 30]
# Цвета:
colors:
- [255, 0, 0] # Красный
- [0, 0, 255] # Синий
- [0, 0, 0] # Чёрный
- [0, 255, 0] # Зеленый
- [255, 0, 255] # Магнетта
- [0, 255, 255] # Циан
- [255, 255, 255] # Белый
- [255, 255, 0] # Желтый